image: node:18.14

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: quay.io/jland/chatbot-docs:latest

build:
  stage: build
  tags:
    - aws
  script:
    - npm ci
    - npx quartz build
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  image: quay.io/podman/stable
  tags:
    - aws
  script:
    - podman login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD quay.io
    - podman build -t $IMAGE_NAME .
    - podman push $IMAGE_NAME